### ISSUE TITLE
Skynet Steam Emulator for MacOS/Linux

### ISSUE THREAD

**Issue by nerohand** [Hackerprod/-SKYNET-Steam-Emulator#4]
Hi @Hackerprod , We want to play dota 2 on the LAN mode with "map dota" and "connect ip" on macos and Linux but this is the build for only windows. We may need the cracked libsteam_api.dylib for macos and libsteam_api.so for linux. Can you build one for us? We are happy to pay for that. Thanks.

**Comment by Hackerprod** [comment]
Hello friend, at this time it is impossible for me to migrate my project to Mono due to my bandwidth, maybe later I can help you
