### ISSUE TITLE
necesito ayuda

### ISSUE THREAD

**Issue by Yoansy2004** [Hackerprod/-SKYNET-Steam-Emulator#9]
alguien me puede explicar que hago cuando descargo esto no veo ejecutable ni nada

**Comment by Yoansy2004** [comment]
alquien porfavor expliquenme q aser para poder usar lo q esta en el repositorio ya descarque todo pero no veo ningun ejecutable .

**Comment by Yoansy2004** [comment]
nadie atiente esto ¿?

**Comment by ElHave247** [comment]
Se ve que no, hay que compilarlo amigo, pero da errores, que  por lo visto no tendran soporte...
![Captura de pantalla_20230222_183825](https://user-images.githubusercontent.com/102565249/220710490-f75fb982-f860-489c-a6ad-089ff61dc91b.png)

**Comment by Hackerprod** [comment]
Hola, el proyecto tiene una versión de prueba (solo el archivo steam_api.dll) en el grupo "Dota2 offline" de Telegram. Como especifiqué en la introducción está en fase de desarrollo aunque hace rato no lo actualizo por problemas personales. Saludos

**Comment by ElHave247** [comment]
Fun``C´´ionando, eso no es lo que vendes en tus post de cs.rin.ru que el proyecto no se pueda ni compilar ya dice todo...

**Comment by Hackerprod** [comment]
En primer lugar yo no vendo nada en ninguna parte (poco me interesa lo que crean) muchos están usando el emulador para dota que mediante telegram lo he compartido pero he dejado de actualizarlo principalmente por personas como tú que solo exigen sin hacer nada por ayudar.

**Comment by ElHave247** [comment]
> En primer lugar yo no vendo nada en ninguna parte (poco me interesa lo que crean) muchos están usando el emulador para dota que mediante telegram lo he compartido pero he dejado de actualizarlo principalmente por personas como tú que solo exigen sin hacer nada por ayudar.

Ah no? en cs.rn.ru nbo tienes un post? anda ya no digo vender literalmente por dinero, si no lo entiendes es por que no quieres, exijir sin ayudar? jjaja para ayudar las cosas tienen que funcionar chapucero y no mentir y prometer algo en un foro cuando no tienes ni el 15% del trabajo echo
